baseurl = "http://agigen.se"
MetaDataFormat = "json"
languageCode = "en-us"
title = "Agigen"
pluralizeListTitles = false

[indexes]
  tag = "tags"
  group = "groups"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 0
    identifier = "main"

[[menu.main]]
    name = "Services"
    identifier = "services"
    weight = 100
    url = "#"

[[menu.main]]
    name = "Web Production"
    parent = "services"
    url = "/services/web-production"
    weight = 100

[[menu.main]]
    name = "Product development"
    parent = "services"
    url = "/services/product-development"
    weight = 200

[[menu.main]]
    name = "Agigen Labs"
    parent = "services"
    url = "/services/labs"
    weight = 300

[[menu.main]]
    name = "Learn more"
    identifier = "about"
    weight = 300
    url = "#"

[[menu.main]]
    name = "Previous Work"
    weight = 200
    url = "/work/"
    parent = "about"

[[menu.main]]
    name = "About us"
    weight = 400
    url = "/about/"
    parent = "about"

[[menu.main]]
    name = "Our diary"
    weight = 450
    url = "/blog/"
    parent = "about"

[[menu.main]]
    name = "Get in touch"
    identifier = "contact"
    weight = 500
    url = "#"

[[menu.main]]
    name = "Contact us"
    url = "/contact/"
    parent = "contact"



